services:
  database-catalog:
    image: "postgres:16.0-alpine3.18"
    hostname: database-catalog
    container_name: postgres-multi-tenant-dynamic-catalog
    env_file:
      - ./.env.development
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"

  database-a:
    image: "postgres:16.0-alpine3.18"
    hostname: database-a
    container_name: postgres-multi-tenant-dynamic-a
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -p 5433
    environment:
      POSTGRES_HOST: database-a
      POSTGRES_PORT: 5433
      POSTGRES_USER: local_user
      POSTGRES_DB: local_database
      POSTGRES_PASSWORD: local_password
    ports:
      - "5433:5433"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"

  database-b:
    image: "postgres:16.0-alpine3.18"
    hostname: database-b
    container_name: postgres-multi-tenant-dynamic-b
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -p 5434
    environment:
      POSTGRES_HOST: database-b
      POSTGRES_PORT: 5434
      POSTGRES_USER: local_user
      POSTGRES_DB: local_database
      POSTGRES_PASSWORD: local_password
    ports:
      - "5434:5434"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
