version: "3.5"

services:
  database:
    image: "postgres:16.0-alpine3.18"
    hostname: database
    container_name: postgres-single-tenant
    environment:
      POSTGRES_DB: local_database
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    deploy:
      resources:
        limits:
          cpus: "1.3"
          memory: "1.3GB"
    network_mode: host

  quarkus-api1:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    hostname: quarkus-api1
    depends_on:
      - database
    environment:
      APP_PORT: 8090
      APP_DATASOURCE_URL: jdbc:postgresql://localhost:5432/local_database
      APP_DATASOURCE_USERNAME: local_user
      APP_DATASOURCE_PASSWORD: local_password
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2GB"
    network_mode: host
