CREATE TABLE IF NOT EXISTS PESSOAS (
    TENANT_ID VARCHAR(10),
    ID UUID CONSTRAINT ID_PK PRIMARY KEY,
    APELIDO VARCHAR(50) UNIQUE,
    NOME VARCHAR(100),
    NASCIMENTO VARCHAR(10),
    STACK TEXT,
    BUSCA_TRGM TEXT GENERATED ALWAYS AS ( LOWER(NOME || APELIDO || STACK) ) STORED,
    CONSTRAINT unique_tenant_apelido UNIQUE (TENANT_ID, APELIDO)
);

CREATE EXTENSION PG_TRGM;
CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_PESSOAS_BUSCA_TGRM ON PESSOAS USING GIST (BUSCA_TRGM GIST_TRGM_OPS(SIGLEN=64));
CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_PESSOAS_TENANT_ID ON PESSOAS (TENANT_ID);
