global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "java-spring"
    metrics_path: "/q/metrics"
    static_configs:
      - targets: ["localhost:8080", "localhost:8081"]
        labels:
          application: java-spring-metrics
