create extension if not exists pg_trgm with schema pg_catalog;

CREATE TABLE IF NOT EXISTS PESSOAS (
    ID UUID CONSTRAINT ID_PK PRIMARY KEY,
    APELIDO VARCHAR(50) UNIQUE,
    NOME VARCHAR(100),
    NASCIMENTO CHAR(10),
    STACK TEXT,
    BUSCA_TRGM TEXT GENERATED ALWAYS AS ( LOWER(NOME || APELIDO || STACK) ) STORED
);

-- CREATE INDEX IF NOT EXISTS IDX_PESSOAS_BUSCA_TGRM ON PESSOAS USING GIST (BUSCA_TRGM GIST_TRGM_OPS(SIGLEN=64));
CREATE INDEX IF NOT EXISTS IDX_PESSOAS_BUSCA_TGRM ON PESSOAS USING GIST (BUSCA_TRGM gist_trgm_ops);
-- CREATE INDEX IF NOT EXISTS IDX_PESSOAS_BUSCA_TRGM ON PESSOAS USING GIN (BUSCA_TRGM gin_trgm_ops);
